export const NICHES = [
  "Motherhood",
  "Nursing/Healthcare",
  "Pregnancy Loss/Grief",
  "Relationships",
  "Fitness & Wellness",
  "Mental Health & Psychology",
  "Personal Finance",
  "Business & Entrepreneurship",
  "Nutrition & Diet",
  "Parenting & Education",
  "Faith & Spirituality",
  "Beauty & Skincare",
  "Career Development",
  "Life Coaching",
  "Content Creation",
] as const;

export type Niche = (typeof NICHES)[number];

export const SUB_NICHES: Record<string, string[]> = {
  "Motherhood": [
    "Postpartum Nutrition",
    "Raw Motherhood/Wellness",
    "Mom Psychology",
    "Mom Therapy/Coaching",
    "Postpartum Fitness",
    "Postpartum Pelvic Floor",
    "Postpartum Movement",
    "Pregnancy Empowerment",
    "Postpartum Therapy",
    "PMDD/Cycle Syncing",
    "Postpartum Identity",
    "Pregnancy Tools",
    "Christian Postpartum",
    "Prenatal/Postnatal Fitness",
    "Birth Preparation",
    "Newborn Care",
  ],
  "Nursing/Healthcare": [
    "Radiology",
    "PA Journey",
    "Aesthetic PA/NP",
    "Health Business",
    "Cardiology Education",
    "Locum Medicine",
    "Lactation/Nutrition",
    "Breastfeeding",
    "Infant Feeding",
    "Travel Nursing",
    "Nurse Entrepreneur",
    "Medical Education",
    "Holistic Medicine",
    "Functional Medicine",
  ],
  "Pregnancy Loss/Grief": [
    "Grief Coaching",
    "Death Doula",
    "Grief + Ritual",
    "Baby Loss Coach",
    "PAL Community",
    "Grief Authority",
    "Miscarriage Support",
    "Stillbirth Support",
    "Infertility Journey",
  ],
  "Relationships": [
    "Mom + Relationships",
    "Parenting + Couples",
    "Therapy/Relationships",
    "Conscious Parenting",
    "Women's Wellness",
    "Motherhood/Lifestyle",
    "Honest Lifestyle",
    "Marriage Coach",
    "Divorce Recovery",
    "Dating Coach",
    "Family Systems",
  ],
  "Fitness & Wellness": [
    "Strength Training",
    "Yoga & Mindfulness",
    "Running & Endurance",
    "Weight Loss Coaching",
    "Body Recomposition",
    "Home Workouts",
    "Pilates",
    "Holistic Wellness",
    "Biohacking",
    "Cycle Syncing",
  ],
  "Mental Health & Psychology": [
    "Anxiety & Stress",
    "Depression Recovery",
    "Trauma & PTSD",
    "ADHD Coaching",
    "Burnout Recovery",
    "Self-Worth & Confidence",
    "Inner Child Work",
    "Nervous System Regulation",
    "Somatic Therapy",
  ],
  "Personal Finance": [
    "Debt Freedom",
    "Investing for Beginners",
    "Budget Coaching",
    "Financial Independence",
    "Side Hustle Income",
    "Real Estate Investing",
    "Crypto Education",
    "Money Mindset",
  ],
  "Business & Entrepreneurship": [
    "Online Business",
    "Course Creation",
    "Digital Products",
    "Coaching Business",
    "E-commerce",
    "Freelancing",
    "Agency Building",
    "Passive Income",
    "Brand Building",
  ],
  "Nutrition & Diet": [
    "Plant-Based Nutrition",
    "Anti-Inflammatory Diet",
    "Gut Health",
    "Sports Nutrition",
    "Intuitive Eating",
    "Weight Management",
    "Hormone Health",
    "Pediatric Nutrition",
  ],
  "Parenting & Education": [
    "Homeschooling",
    "Gentle Parenting",
    "Child Development",
    "Special Needs Parenting",
    "Teen Parenting",
    "Toddler Development",
    "Educational Activities",
  ],
  "Faith & Spirituality": [
    "Christian Lifestyle",
    "Christian Parenting",
    "Faith + Wellness",
    "Biblical Womanhood",
    "Spiritual Growth",
    "Mindfulness & Meditation",
    "New Age Spirituality",
  ],
  "Beauty & Skincare": [
    "Clean Beauty",
    "Skincare Education",
    "Anti-Aging",
    "Aesthetic Medicine",
    "Makeup Artistry",
    "Hair Care",
    "Natural Beauty",
  ],
  "Career Development": [
    "Corporate to Entrepreneur",
    "Resume & Job Search",
    "Leadership Coaching",
    "Women in Tech",
    "Healthcare Career",
    "Remote Work",
    "Work-Life Balance",
  ],
  "Life Coaching": [
    "Mindset Coaching",
    "Productivity & Goals",
    "Habit Formation",
    "Purpose & Fulfillment",
    "Confidence Building",
    "Boundary Setting",
    "Lifestyle Design",
  ],
  "Content Creation": [
    "Instagram Growth",
    "TikTok Strategy",
    "YouTube Education",
    "Podcast Building",
    "Newsletter Marketing",
    "Personal Branding",
    "UGC Creator",
    "Social Media Management",
  ],
};
